### ISSUE TITLE
Reduce steps in templates and static folder naming

### ISSUE THREAD

**Issue by AbhilakshSinghReen** [DERaC-IO/DeracioTSS#4]
While configuring the templates folder, the CLI first asks whether or not the default folder name is to be used, if the user selects no then it asks for a folder name. This requires 2 inputs from the user. The same also happens while configuring the static folder.

We can reduce this to one input by taking the input just like we take the input for the port: give a default value that the user can change if they wish.

@ts0924 Sir, if you think we should make this change, please assign this issue to me and I will be more than happy to work on it.

**Comment by ts0924** [comment]
@AbhilakshSinghReen I've changed and release it in the coming version, thanks!

**Comment by AbhilakshSinghReen** [comment]
This issue has been fixed and I am closing it now.
